.TH man 8 "June 2017" "1.0" "innervate man page"
.SH NAME
innervate \- User workload simulation for OpenShift
.SH SYNOPSIS
innv
.SH DESCRIPTION
Innervate simulates user load when deployed in an OpenShift cluster, including
deploying, undeploying, and scaling services.
.SH OPTIONS
Running innv -h will display all valid options.
.SH AUTHOR
Jay Dobies (jdobies@redhat.com)
