host: kubernetes
port: 8443
users:
 - username: user
   password: user
 - username: user2
   password: user2
scenarios:
 - name: create-service
   type: CreateService
   config:
     image_list: kubernetes/guestbook
     max_services_per_user: 3
