host: kubernetes
port: 8443
users:
  - username: user1
    password: user1
  - username: user2
    password: user2
scenarios:
  - name: create-service
    type: CreateService
    config:
      image_list: kubernetes/guestbook
      ports: 3000:TCP
      max_services_per_user: 3
  - name: create-project
    type: CreateProject
    config:
      max_projects_per_user: 5
  - name: delete-project
    type: DeleteProject
  - name: delete-service
    type: DeleteService
logging:
  version: 1
  formatters:
    basic:
      format: "%(asctime)s %(levelname)-8s %(message)s"
    detailed:
      format: "%(asctime)s %(levelname)-8s %(name)-12s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: basic
      level: DEBUG
  loggers:
    innervate:
      level: DEBUG
      handlers:
        - console
